config/routes.rb
Rails.application.routes.draw do


  resources :promos do          #notebooks
    resources :classrooms do    #pages
      resources :students do       #checklists
        resources :student_invoices #checklist_items
      end
    end
  end

  devise_for :users, controllers: { registrations: "users/registrations"}
  root to:'promos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student_invoice.rb
class StudentInvoice < ApplicationRecord
  belongs_to :student

  #VALIDATIONS
  validates :status, inclusion: { in: ['not-started', 'in-progress', 'complete'] }
  validates_presence_of :status


  #CONSTANTES
  STATUS_OPTIONS = [
    ['Not started', 'not-started'],
    ['In progress', 'in-progress'],
    ['Complete', 'complete']
  ]


  #READABLES OF STATUS
  def readable_status
    case status
    when 'not-started'
      'Not started'
    when 'in-progress'
      'In progress'
    when 'complete'
      'Complete'
    end
  end

  #COLORS
  def color_class
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'primary'
    when 'complete'
      'dark'
    end
  end

  def complete?
    status == 'complete'
  end

  def in_progress?
    status == 'in-progress'
  end
end

app/controllers/student_invoices_controller.rb
class StudentInvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_student_invoice, only: [:update, :destroy]


  # POST /student_invoices
  def create
    promo = curent_user.promos.friendly.find(params[:promo_id])
    classroom = promo.classrooms.friendly.find(params[:classroom_id])
    student = classroom.students.friendly.find(params[:student_id])
    student_invoice = student.student_invoices.new(student_invoice_params)
    student_invoice.status= "not-started"
    student_invoice.save
    redirect_to promo_classroom_path(promo, classroom)
  end

  def update
     if @student_invoice.update(student_invoice_params)
      redirect_to @student_invoice, notice: 'paiement was successfully updated.'
    else
      render :edit
    end
  end


  # DELETE /student_invoices/1
  def destroy
    promo = current_user.promos.friendly.find(params[:promo_id])
    classroom = promo.classrooms.friendly.find(params[:classroom_id])
    student = classrom.students.friendly.find(params[student_id])
    student_invoice = student.student_invoices.find(params[:id])
    student_invoice.destroy
    redirect_to promo_classroom_path(promo, classroom)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_invoice
      @student_invoice = StudentInvoice.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def student_invoice_params
      params.require(:student_invoice).permit(:solde, :operation, :invoice, :status, :student_id)
    end

end

app/helpers/student_invoices_helper.rb
module StudentInvoicesHelper
end

app/views/student_invoices/_form.html.erb
<div class="dropdown-menu">

<%= form_with(model: [promo, classroom, student, student_invoice], local: true, html:{ class: "px-2 py-2"}) do |form| %>
    <% if @student_invoice.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(student_invoice.errors.count, "error") %> prohibited this student_invoice from being saved:</h2>

        <ul>
          <% student_invoice.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field">
    <%= form.label :solde %>
    <%= form.number_field :solde %>
  </div>

  <div class="field">
    <%= form.label :operation %>
    <%= form.number_field :operation %>
  </div>

  <div class="form-group">
    <%= form.label :invoice %>
    <%= form.text_field :invoice %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.text_field :status, placeholder:"Statuts" %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/student_invoices/_invoice.html.erb
<ul class='list-group'>
        <!-- loop to print checklist_item/!-->
        <% student.student_invoices.each do |student_invoice| %>
          <% if checklist_item.persisted? %>
            <li class='list-group-item d-flex justify-content-between'>
              <span><%= student_invoice.title %></span>
              <span>STATUS</span>
              <span>OPERATION</span>
              <div>
                <div class="dropdown float-left mr-4">
                  <!-- Options/!-->

                  <button class="btn btn-sm mr-1 btn-outline-<%= student_invoice.color_class %> dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= student_invoice.readable_status %>
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <% StudentInvoice::STATUS_OPTIONS.each do |status| %>
                      <a class="dropdown-item" href="#"
                      data-reflex="click->StudentInvoiceReflex#change_status"
                      data-id="<%= student_invoice.id %>"
                      data-status="<%= status[1] %>">
                        <%= status[0] %>

                      </a>
                    <% end %>
                  </div>
                </div>

                <!-- delete option/!-->

                <%= link_to promo_classroom_student_student_invoice_path(promo, classroom, student, student_invoice), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class='fas fa-times text-secondary'></i>
                <% end %>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>

app/views/student_invoices/edit.html.erb
<h1>Editing Student Invoice</h1>

<%= render 'form', student_invoice: @student_invoice %>

<%= link_to 'Show', @student_invoice %> |
<%= link_to 'Back', student_invoices_path %>

app/views/student_invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Solde</th>
      <th>Operation</th>
      <th>Invoice</th>
      <th>Status</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_invoices.each do |student_invoice| %>
      <tr>
        <td><%= student_invoice.solde %></td>
        <td><%= student_invoice.operation %></td>
        <td><%= student_invoice.invoice %></td>
        <td><%= student_invoice.status %></td>
        <td><%= student_invoice.student_id %></td>
        <td><%= link_to 'Show', student_invoice %></td>
        <td><%= link_to 'Edit', edit_student_invoice_path(student_invoice) %></td>
        <td><%= link_to 'Destroy', student_invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student Invoice', new_student_invoice_path %>

app/views/student_invoices/new.html.erb
<h1>New Student Invoice</h1>

<%= render 'form', student_invoice: @student_invoice %>

<%= link_to 'Back', student_invoices_path %>

app/views/student_invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Solde:</strong>
  <%= @student_invoice.solde %>
</p>

<p>
  <strong>Operation:</strong>
  <%= @student_invoice.operation %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @student_invoice.invoice %>
</p>

<p>
  <strong>Status:</strong>
  <%= @student_invoice.status %>
</p>

<p>
  <strong>Student:</strong>
  <%= @student_invoice.student_id %>
</p>

<%= link_to 'Edit', edit_student_invoice_path(@student_invoice) %> |
<%= link_to 'Back', student_invoices_path %>