config/routes.rb
Rails.application.routes.draw do


  resources :promos do          #notebooks
    resources :classrooms do    #pages
      resources :students do       #checklists
        resources :student_invoices #checklist_items
      end
    end
  end

  devise_for :users, controllers: { registrations: "users/registrations"}
  root to:'promos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/membership/_sign_in.html.erb
<% content_for @title= "Connecter" %>

<div class="col-8 col-md-4 col-lg-6 register-form">
    <div class="form container ">
        <div class="note">
            <p>Connexion</p>
        </div>
        <div class="form-content">
                <div class=" jsutigfy-content">
                    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                          <div class="form-group">
                             <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "chatln@gmail.com" %>
                          </div>
                          <div class="form-group">
                            <%= f.password_field :password, autocomplete: "current-password", class: "form-control", placeholder: "Your Password *" %>
                        </div>
                          <% if devise_mapping.rememberable? %>
                            <div class="field">
                              <%= f.check_box :remember_me %>
                              <%= f.label :remember_me %>
                            </div>
                          <% end %>
                      <div class="actions">
                        <%= f.submit "Connecter", class: " btn btnSubmit" %>
                      </div>
                    <% end %>
                </div>

        </div>
    </div>
</div>

app/views/shared/membership/_sign_up.html.erb
<% content_for @title= "Créer un Compte" %>
<div class="container register">
    <div class="row">
        <div class="col-md-3 register-left">
            <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
            <h3>Bienvenu sur <span class="font-semibold">LNKARA</span></h3>
            <p>Vous êtes à 30 secondes de gagner votre propre argent!</p>
            <input type="submit" name="" value="Login"/>
            <br/>
        </div>
        <!-- option/!-->
        <div class="col-md-9 register-right">
            <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Directeur</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Personnel</a>
                </li>
            </ul>
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                <h3 class="register-heading">Creer Un compte</h3>
                <div class="row register-form">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="First Name *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Last Name *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="Password *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control"  placeholder="Confirm Password *" value="" />
                        </div>
                        <div class="form-group">
                            <div class="maxl">
                                <label class="radio inline">
                                    <input type="radio" name="gender" value="male" checked>
                                    <span> Male </span>
                                </label>
                                <label class="radio inline">
                                    <input type="radio" name="gender" value="female">
                                    <span>Female </span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Your Email *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" minlength="10" maxlength="10" name="txtEmpPhone" class="form-control" placeholder="Your Phone *" value="" />
                        </div>
                        <div class="form-group">
                            <select class="form-control">
                                <option class="hidden"  selected disabled>Please select your Sequrity Question</option>
                                <option>What is your Birthdate?</option>
                                <option>What is Your old Phone Number</option>
                                <option>What is your Pet Name?</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Enter Your Answer *" value="" />
                        </div>
                            <input type="submit" class="btnRegister"  value="Register"/>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade show" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                    <h3  class="register-heading">Apply as a Hirer</h3>
                    <div class="row register-form">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="First Name *" value="" />
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Last Name *" value="" />
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control" placeholder="Email *" value="" />
                            </div>
                            <div class="form-group">
                                <input type="text" maxlength="10" minlength="10" class="form-control" placeholder="Phone *" value="" />
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="password" class="form-control" placeholder="Password *" value="" />
                            </div>
œ                           <div class="form-group">
                                <input type="password" class="form-control" placeholder="Confirm Password *" value="" />
                            </div>
                            <div class="form-group">
                                <select class="form-control">
                                    <option class="hidden"  selected disabled>Please select your Sequrity Question</option>
                                    <option>What is your Birthdate?</option>
                                    <option>What is Your old Phone Number</option>
                                    <option>What is your Pet Name?</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="`Answer *" value="" />
                            </div>
                            <%= f.submit "Créer Compte" , class: "btn btn-success" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<% end %>
    </div>
</div>