config/routes.rb
Rails.application.routes.draw do


  resources :promos do          #notebooks
    resources :classrooms do    #pages
      resources :students do       #checklists
        resources :student_invoices #checklist_items
      end
    end
  end

  devise_for :users, controllers: { registrations: "users/registrations"}
  root to:'promos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/promo.rb
class Promo < ApplicationRecord

  #RELATIONS
  belongs_to :user
  has_many :classrooms, dependent: :destroy


  #slug
  extend FriendlyId
    friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
      title_changed?
  end
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
    before_action :authenticate_user!
    before_action :set_promo, only: [:show, :edit, :update, :destroy]

  # GET /promos
  def index
    @promos = current_user.promos
  end

  # GET /promos/1
  def show

  end

  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  # POST /promos
  def create
    #@promo.code_school = current_user.code_school
    @promo = current_user.promos.build(promo_params)

    if @promo.save
      redirect_to @promo, notice: 'Promo was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /promos/1
  def update
    if @promo.update(promo_params)
      redirect_to @promo, notice: 'Promo was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /promos/1
  def destroy
    @promo.destroy
    redirect_to promos_url, notice: 'Promo was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo
      @promo = current_user.promos.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def promo_params
      params.require(:promo).permit(:title)
    end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_form.html.erb
<%= form_with(model: promo, local: true) do |form| %>
  <% if promo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(promo.errors.count, "error") %> prohibited this promo from being saved:</h2>

      <ul>
        <% promo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/promos/edit.html.erb
<h3>
  Editer la promotion
  <%= link_to 'View', @promo, class: 'btn btn-outline-primary' %>
</h3>

<%= render 'form', promo: @promo %>

app/views/promos/index.html.erb
<% content_for @title= "Accueil" %>

<div class="card mt-40">

</div>
<h3 class='d-flex justify-content-between m-2'>
  <span>Promotions</span>
  <%= link_to  new_promo_path, class: 'btn btn-outline-primary' do %>
  <i class="fa fa-plus-circle" aria-hidden="true"></i> Promotion
  <% end %>
</h3>

<div class="row">
  <% @promos.each do |promo| %>
    <div class="col-md-4">
        <div class="card border-dark mb-2">
          <div class="card-body">
            <h5 class='card-title d-flex justify-content-between'>
              <%= link_to promo do %>
                <button type="button" class="btn bg-gray-300 rounded-r rounded-l">
                  Promotion <span class="badge badge-light"><%= promo.title %></span>
                </button>
              <% end %>
              <div class="dropdown">
                <button class="btn btn-light" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-ellipsis-h"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                  <%= link_to 'Edit', edit_promo_path(promo), class: 'dropdown-item' %>
                  <%= link_to 'Delete', promo, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item' %>
                </div>
              </div>
            </h5>
            <div class="stats mb-4">
              <p class='classroom-count'><%= promo.classrooms.count %> classes</p>

            </div>
            <%= link_to  promo, class: 'btn btn-outline-info' do %>
              <i class="fa fa-plus-circle" aria-hidden="true"></i> Voir Plus
            <% end %>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/promos/new.html.erb
<h3>New Promo</h3>

<%= render 'form', promo: @promo %>

app/views/promos/show.html.erb
<div class="card mt-32"></div>
<h3 class='mb-4 font-bold'>
  <%= link_to 'Back', promos_path, class: 'btn btn-secondary mb-3' %>
  <%= link_to  edit_promo_path(@promo), class: 'btn btn-outline-primary'  do %>
    Classes <%= @promo.title %>
  <% end %>
</h3>



<h5 class='d-flex justify-content-between m-4'>
  <span>Les classes</span>
  <%= link_to 'Créer une Classe', new_promo_classroom_path(@promo), class: 'btn btn-outline-primary' %>
</h5>

<div class="row">
  <% @promo.classrooms.each do |classroom| %>
    <div class="col-md-4">
        <div class="card border-dark mb-2">
          <div class="card-body">
            <h5 class='card-title d-flex justify-content-between'>
              <%= link_to promo_classroom_path(@promo, classroom) do %>
                <button type="button" class="btn bg-gray-300 rounded-r rounded-l">
                  <span class="badge badge-light">Classe <%= classroom.title %></span>
                </button>
              <% end %>
              <div class="dropdown">
                <button class="btn btn-light" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-ellipsis-h"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                  <%= link_to 'Editer', edit_promo_classroom_path(@promo, classroom), class: 'dropdown-item' %>
                  <%= link_to 'Delete', promo_classroom_path(@promo, classroom), method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item' %>
                </div>
              </div>
            </h5>

            <%= link_to  promo_classroom_path(@promo, classroom), class: 'btn btn-outline-info' do %>
              <i class="fa fa-plus-circle" aria-hidden="true"></i> Voir Plus
            <% end %>
          </div>
        </div>
    </div>
  <% end %>